# Clase 3

* Funciones de secuencia.
* Ciclos.
* Condicionales if, elif, else.
* Manejo de DataFrame con pandas.

In [1]:
import pandas as pd # Manejo de DataFrame
import numpy as np # Manejo matricial

# Funciones de secuencia

En Python por defecto existe una función llamada range, que crea una secuencia entre dos núemros enteros, pero funciona como un intervalo \[inicio , fin\)

In [2]:
range(5) # Secuencia de 0 hasta 4, 5 elementos

range(0, 5)

In [3]:
list(range(5)) # Transformar la secuencia en una lista

[0, 1, 2, 3, 4]

In [4]:
range(5,10) # Secuencia de números desde 5 hasta 9

range(5, 10)

In [5]:
list(range(0,10) ) # Transformar la secuencia en una lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

También es posible realizar secuencias con numpy, donde se tienen mas variedad de opciones. También es de la misma manera de intervalo [inicio, fin), pero tiene la posibilidad de realizar un salto para la secuencia.

In [6]:
np.arange(start= 1 ,stop=10 ) # Secuencia 1 hasta 9, se crea un vector.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(start= 1 ,stop=50,step=5 ) # Secuencia 1 hasta 49, salto de 5.

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

Cuando se quiere repetir valores, es posible realizarlo con listas.

In [8]:
[ "Pedro" , 50] *5 # Repite 5 veces

['Pedro', 50, 'Pedro', 50, 'Pedro', 50, 'Pedro', 50, 'Pedro', 50]

In [9]:
[5]*10 # Repetir un solo valor en una lista

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [10]:
np.repeat( [1,2,3], 10  ) # repetir cada valor 10 veces

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3])

# Ciclos

Los ciclos son una forma de repetir un bloque de código un número determinado de veces o hasta que se cumpla una condición.


## For

Con los ciclos for, se debe especificar un arreglo en específico donde se realizará un recorrido por dicho arreglo.


In [11]:
for i in range(5): # Recorrido desde 0 hasta 4
  print(i )

0
1
2
3
4


In [12]:
for i in [1,3,5,7]: # Recorrido en la lista
  print( i)

1
3
5
7


In [13]:
for i in np.array([ 0,1,7] ):
  print(i)

0
1
7


In [14]:
for i in ["Pedro", "Antonio", "Sara" ]:
  print(i )

Pedro
Antonio
Sara


Cuando tenemos dos listas del mismo tamaño y queremos hacer un recorrido por ambas listas, range(len(lista)) nos permite tener una secuencia de todos los índices de la lista y con esta, se podrá realizar el recorrido por ambas listas.

In [15]:
lista= ["Pedro", 15, "Juan", 20]
for i in range(len(lista) ):
  print( lista[i ])

Pedro
15
Juan
20


In [16]:
lista_1 = [20,30,50] # Lista 1
lista_2 = [500,60, 60] # lista 2
sum_list = [] # Lista vacia
for i in range(len(lista_1)): # Recorrido  desde 0 hasta la el tamaño de la lista -1
# código ejecución
  suma= lista_1[i] + lista_2[i] # sumamos los elementos
  sum_list.append(suma )  # Añadimos la suma a la nueva lista.
sum_list

[520, 90, 110]

## While

Este tipo de ciclos, realiza una secuencia de códigos mientras se cumpla la condición, en el momento que no se cumpla la condición termina el ciclo.

In [17]:
x = 10
while x > 0 :  # Este ciclo se repite mientras el valor de x sea mayor que 0
    print(x) # Muestra resultados
    x = x - 1 # Código ejecución

10
9
8
7
6
5
4
3
2
1


# Condicionales if, else

Los condicionales if, elif y else, realizar la ejecución de un código si se cumple.


In [18]:
x= 15
if x > 10:
  print("Es mayor que 10")
elif x<= 10:
  print( "Es menor o igual que 10")
else:
  print("Error")

Es mayor que 10


In [19]:
x= 5
if x > 10:
  print("Es mayor que 10")
elif x<= 10:
  print( "Es menor o igual que 10")

Es menor o igual que 10


¿Cómo se pueden convinar los ciclos y condicionales?


Supongamos que se una lista de estudiantes, se tiene la nota de un examen final, puntos extra y se quiere saber la lista de los estudiantes que pasaron el examen sin los puntos extra y los que pasaron con los puntos extra.  

In [20]:
lista_estudiantes= ["Alejandro", "Mateo","Luis", "Laura", "Tatiana", "Pedro", "Santiago","Luciana"] # Estudiantes
lista_notas= [4.2,3.2,2.5,3.4,2,1.5,2.9,2.9] # Nota del examen
lista_puntos_extra = [ 0 , 0.1,0.6,0.3,0.4,0.3,0,0.2] # Puntos adicionales
# Creamos la lista vacia
lista_aprobados_sin_puntos_extra=[]
lista_aprobados_con_puntos_extra=[]
for i in range(len(lista_estudiantes)):  # Paramos por un recorrido desde el primer estudiante hasta el último
  # Bloque de código
  nota =lista_notas[i]  # Nota del estudiante
  puntos_extra= lista_puntos_extra[i] # puntos extra
  if nota >=3 : # si la nota del examen mayor o igual a 3, aprueba sin puntos extra
    lista_aprobados_sin_puntos_extra.append(lista_estudiantes[i] )
    # sino se cumple entonces:
  elif(nota + puntos_extra ) >=3: # Si la nota mas los puntos extra son mayor o igual a 3, aprueba con puntos extra.
    lista_aprobados_con_puntos_extra.append(lista_estudiantes[i]  )

print("Lista de estudiantes que aprobaron sin puntos extra" )
print(lista_aprobados_sin_puntos_extra)
print("Lista de estudiantes que aprobaron con puntos extra")
print(lista_aprobados_con_puntos_extra )

Lista de estudiantes que aprobaron sin puntos extra
['Alejandro', 'Mateo', 'Laura']
Lista de estudiantes que aprobaron con puntos extra
['Luis', 'Luciana']


# DataFrame

En esta sección se utilizaran las herramientas de pandas para crear columnas, filas, realizar filtros y eliminar registros.

Utilizando el ejemplo anterior ¿cómo es posible extraer dicha información si se tuviera la información en un Dataframe?

In [21]:
datos_notas= pd.DataFrame({"notas":lista_notas,
                           "puntos extra": lista_puntos_extra},
                          index= lista_estudiantes  )

In [22]:
datos_notas["notas"]+datos_notas["puntos extra"]  # Suma de columnas

Alejandro    4.2
Mateo        3.3
Luis         3.1
Laura        3.7
Tatiana      2.4
Pedro        1.8
Santiago     2.9
Luciana      3.1
dtype: float64

In [23]:
datos_notas.sum(axis=1 ) # Sumando todas las columnas

Alejandro    4.2
Mateo        3.3
Luis         3.1
Laura        3.7
Tatiana      2.4
Pedro        1.8
Santiago     2.9
Luciana      3.1
dtype: float64

In [24]:
datos_notas["nota final"] = datos_notas.sum(axis=1) # Crear una nueva columna

In [25]:
filtro_aprobados_sin_puntos_extra = datos_notas["notas" ] >= 3
filtro_aprobados_con_puntos_extra =datos_notas["nota final"] >= 3

Una forma de filtrar el dataframe con pandas es utilizando [ ] o utilizando .loc[].


In [26]:
datos_notas["nota final"] # seleccionar una columna

Alejandro    4.2
Mateo        3.3
Luis         3.1
Laura        3.7
Tatiana      2.4
Pedro        1.8
Santiago     2.9
Luciana      3.1
Name: nota final, dtype: float64

In [27]:
filtro_aprobados_sin_puntos_extra # los estudiantes que aprobaron sin puntos extra

Alejandro     True
Mateo         True
Luis         False
Laura         True
Tatiana      False
Pedro        False
Santiago     False
Luciana      False
Name: notas, dtype: bool

Cuando tenemos un dataframe con pandas, para seleccionar una columna utilizamos los corchetes.

```python
datos["Variable"]
```

Sin embargo nosotros podemos filtrar utilizando los chorchetes, donde se puede introducir un arreglo de booleanos.

```python
filtro= [ True, False, False, ..., True ]
datos[filtro]
```
Esto me arroja los datos con todas las columnas, pero aplicando el filtro y mostrando unicamente los individuos que tienen True en el filtro.



In [28]:
datos_notas[filtro_aprobados_sin_puntos_extra] # Selecciona los que

notas  puntos extra  nota final
Alejandro    4.2           0.0         4.2
Mateo        3.2           0.1         3.3
Laura        3.4           0.3         3.7

In [29]:
filtro_aprobados_con_puntos_extra # Los estudiantes que aprueban con puntos extra

Alejandro     True
Mateo         True
Luis          True
Laura         True
Tatiana      False
Pedro        False
Santiago     False
Luciana       True
Name: nota final, dtype: bool

In [30]:
datos_notas[filtro_aprobados_con_puntos_extra] # No considera a Tatiana, Pedro y Santiago

notas  puntos extra  nota final
Alejandro    4.2           0.0         4.2
Mateo        3.2           0.1         3.3
Luis         2.5           0.6         3.1
Laura        3.4           0.3         3.7
Luciana      2.9           0.2         3.1

Pero ¿cómo podemos hacer que seleccione los estudiantes que pasaron el examen gracias a los puntos extra?

In [31]:
filtro_aprobados_por_puntos_Extra =  ~filtro_aprobados_sin_puntos_extra & filtro_aprobados_con_puntos_extra # A

In [32]:
datos_notas[filtro_aprobados_por_puntos_Extra] # Filtrando los estudiantes que aprobaron gracias a los puntos extra

notas  puntos extra  nota final
Luis       2.5           0.6         3.1
Luciana    2.9           0.2         3.1

In [33]:
datos_notas.loc[ filtro_aprobados_por_puntos_Extra, ["nota final"] ] # con .loc podemos realizar el filtro y seleccionar columnas

nota final
Luis            3.1
Luciana         3.1

Se puede crear una nueva columna especificando una variable como caracter, númerica, boolenado. Esto indica que es una variable de una dimensión, pero se lo asignara a todas las filas

In [34]:
datos_notas["Periodo"] = "Primero" # Crear una nueva columnas

In [35]:
datos_notas

notas  puntos extra  nota final  Periodo
Alejandro    4.2           0.0         4.2  Primero
Mateo        3.2           0.1         3.3  Primero
Luis         2.5           0.6         3.1  Primero
Laura        3.4           0.3         3.7  Primero
Tatiana      2.0           0.4         2.4  Primero
Pedro        1.5           0.3         1.8  Primero
Santiago     2.9           0.0         2.9  Primero
Luciana      2.9           0.2         3.1  Primero

También podemos añadir nuevas filas utilizando .loc


In [36]:
datos_notas.loc["Tania", ["Periodo"] ] = "Segundo" # Creamos una

In [37]:
datos_notas

notas  puntos extra  nota final  Periodo
Alejandro    4.2           0.0         4.2  Primero
Mateo        3.2           0.1         3.3  Primero
Luis         2.5           0.6         3.1  Primero
Laura        3.4           0.3         3.7  Primero
Tatiana      2.0           0.4         2.4  Primero
Pedro        1.5           0.3         1.8  Primero
Santiago     2.9           0.0         2.9  Primero
Luciana      2.9           0.2         3.1  Primero
Tania        NaN           NaN         NaN  Segundo

Podemos observar que creamos un registro, para Tania (no existe en los índices) y le asignamos un valor a una sola columna. Los demás registros se asumen como registros faltantes (NA).

In [38]:
datos_notas.loc["Tania", ["notas", "puntos extra", "nota final"] ] = [ 1.9,0.3,2.2]
datos_notas

notas  puntos extra  nota final  Periodo
Alejandro    4.2           0.0         4.2  Primero
Mateo        3.2           0.1         3.3  Primero
Luis         2.5           0.6         3.1  Primero
Laura        3.4           0.3         3.7  Primero
Tatiana      2.0           0.4         2.4  Primero
Pedro        1.5           0.3         1.8  Primero
Santiago     2.9           0.0         2.9  Primero
Luciana      2.9           0.2         3.1  Primero
Tania        1.9           0.3         2.2  Segundo

Se puede crear una nueva fila asignando un indice que no se encuentre en los datos.

In [39]:
datos_notas.loc[0 ,["notas"] ] = 0.2 #

In [40]:
datos_notas

notas  puntos extra  nota final  Periodo
Alejandro    4.2           0.0         4.2  Primero
Mateo        3.2           0.1         3.3  Primero
Luis         2.5           0.6         3.1  Primero
Laura        3.4           0.3         3.7  Primero
Tatiana      2.0           0.4         2.4  Primero
Pedro        1.5           0.3         1.8  Primero
Santiago     2.9           0.0         2.9  Primero
Luciana      2.9           0.2         3.1  Primero
Tania        1.9           0.3         2.2  Segundo
0            0.2           NaN         NaN      NaN

In [41]:
datos_notas.dropna( )

notas  puntos extra  nota final  Periodo
Alejandro    4.2           0.0         4.2  Primero
Mateo        3.2           0.1         3.3  Primero
Luis         2.5           0.6         3.1  Primero
Laura        3.4           0.3         3.7  Primero
Tatiana      2.0           0.4         2.4  Primero
Pedro        1.5           0.3         1.8  Primero
Santiago     2.9           0.0         2.9  Primero
Luciana      2.9           0.2         3.1  Primero
Tania        1.9           0.3         2.2  Segundo